# name: text_digitization_app
# description: A Flutter app for text extraction and persistent storage
# version: 1.0.0+1

# environment:
#   sdk: '>=3.0.0 <4.0.0'

# dependencies:
#   flutter:
#     sdk: flutter
#   hive: ^2.2.3
#   hive_flutter: ^1.1.0
#   intl: ^0.19.0
#   image_picker: ^1.0.4
#   path_provider: ^2.1.1
#   http: ^1.1.0
#   google_fonts: ^6.1.0

# dev_dependencies:
#   flutter_test:
#     sdk: flutter
#   hive_generator: ^2.0.0
#   build_runner: ^2.4.6

# flutter:
#   uses-material-design: true

name: text_digitization_app
description: A Flutter app for text extraction and persistent storage
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  google_sign_in: ^6.1.5
  pdf: ^3.10.8
  # open_file: ^3.3.2
  # share_plus: ^11.0.0 
  open_filex: ^4.3.2
  image: ^4.5.4 
  intl: ^0.20.2
  image_picker: ^1.0.4
  path_provider: ^2.1.1
  http: ^1.1.0
  google_fonts: ^6.1.0
  # firebase_core: ^3.5.0
  # firebase_auth: ^4.6.2
  firebase_core: ^2.25.4
  firebase_auth: ^4.17.4
  cloud_firestore: ^4.0.0
  share_plus: ^10.0.0
  provider: ^6.0.0
  js: ^0.7.2
  flutter_secure_storage: ^10.0.0-beta.4
  flutter_web_plugins:
    sdk: flutter
  shared_preferences: ^2.0.0 # <-- Add this line for shared_preferences
  url_launcher: ^6.3.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.0
  build_runner: ^2.4.6

flutter:
  uses-material-design: true
  assets:
    - assets/images/doctor.png
    - assets/images/background.png

